type: object
required:
- domain
- categories
properties:
  domain:
    type: string
  description:
    type: string
  categories:
    type: array
    items:
      enum:
      - academia
      - activism
      - adult
      - art
      - books
      - food
      - furry
      - games
      - general
      - hobby
      - humor
      - journalism
      - lgbt
      - music
      - bipoc
      - regional
      - religion
      - science
      - sports
      - tech
      - science
  languages:
    type: array
    items:
      type: string
  region:
    enum:
    - europe
    - north_america
    - south_america
    - africa
    - asia
    - oceania
  legal_body_type:
    enum:
    - natural
    - juridicial
additionalProperties: false
