type: object
required:
- domain
- categories
properties:
  domain:
    type: string
  description:
    type: string
  categories:
    type: array
    items:
      enum:
      - academia
      - activism
      - adult
      - art
      - books
      - food
      - furry
      - games
      - general
      - hobby
      - humor
      - journalism
      - lgbt
      - music
      - bipoc
      - regional
      - religion
      - sports
      - tech
  languages:
    type: array
    items:
      enum:
      - ar
      - ast
      - bg
      - bn
      - br
      - ca
      - co
      - cs
      - cy
      - da
      - de
      - el
      - en
      - eo
      - es
      - et
      - eu
      - fa
      - fi
      - fr
      - ga
      - gl
      - he
      - hi
      - hr
      - hu
      - hy
      - id
      - io
      - is
      - it
      - ja
      - ka
      - kab
      - kk
      - kn
      - ko
      - lt
      - lv
      - mk
      - ml
      - mr
      - ms
      - nl
      - nn
      - no
      - oc
      - pl
      - pt
      - ro
      - ru
      - sk
      - sl
      - sq
      - sr
      - sv
      - szl
      - ta
      - tai
      - te
      - th
      - tr
      - ug
      - uk
      - ur
      - vi
      - zh
  region:
    enum:
    - europe
    - north_america
    - south_america
    - africa
    - asia
    - oceania
  legal_body_type:
    enum:
    - natural
    - juridicial
additionalProperties: false
