name: "New Server Form"
description: "Request a new server addition to the Mastodon Server Directory"
title: "[NEW SERVER]: "
labels: ["new_server"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form completely in order to request a new server addition to the Mastodon Server Directory.

  - type: input
    id: domain
    attributes:
      label: "Domain name"
      description: "Domain name for your Mastodon server (e.g. mastodon.social)"
    validations:
      required: true

  - type: dropdown
    id: categories
    attributes:
      label: "Categories"
      description: "Select all valid categories, you must select at least one, you may select multiple categories."
      multiple: true
      options:
        - academia
        - activism
        - adult
        - art
        - bipoc
        - books
        - food
        - furry
        - games
        - general
        - hobby
        - humor
        - journalism
        - lgbt
        - music
        - regional
        - religion
        - sports
        - tech
    validations:
      required: true

  - type: dropdown
    id: region
    attributes:
      label: "Region"
      descripion: "Select the most appropriate region for your server. You may select none."
      multiple: false
      options:
        - africa
        - asia
        - europe
        - north_america
        - oceania
        - south_america
    validations:
      required: false

  - type: dropdown
    id: language
    attributes:
      label: "Language"
      description: "Select a language (or languages) for your server. You may select none (we will interpret that as no preference), you do not need to select them all."
      multiple: true
      options:
        - Abkhazian (ab)
        - Afar (aa)
        - Afrikaans (af)
        - Akan (ak)
        - Albanian (sq)
        - Amharic (am)
        - Arabic (ar)
        - Aragonese (an)
        - Armenian (hy)
        - Assamese (as)
        - Avaric (av)
        - Avestan (ae)
        - Aymara (ay)
        - Azerbaijani (az)
        - Bambara (bm)
        - Bashkir (ba)
        - Basque (eu)
        - Belarusian (be)
        - Bengali (bn)
        - Bislama (bi)
        - Bosnian (bs)
        - Breton (br)
        - Bulgarian (bg)
        - Burmese (my)
        - Catalan (ca)
        - Central Khmer (km)
        - Chamorro (ch)
        - Chechen (ce)
        - Chichewa (ny)
        - Chinese (zh)
        - Church Slavonic (cu)
        - Chuvash (cv)
        - Cornish (kw)
        - Corsican (co)
        - Cree (cr)
        - Croatian (hr)
        - Czech (cs)
        - Danish (da)
        - Divehi (dv)
        - Dutch (nl)
        - Dzongkha (dz)
        - English (en)
        - Esperanto (eo)
        - Estonian (et)
        - Ewe (ee)
        - Faroese (fo)
        - Fijian (fj)
        - Finnish (fi)
        - French (fr)
        - Fulah (ff)
        - Gaelic (gd)
        - Galactic Standard (gs)
        - Gallifreyan (gf)
        - Galician (gl)
        - Ganda (lg)
        - Georgian (ka)
        - German (de)
        - Greek (el)
        - Guaraní (gn)
        - Gujarati (gu)
        - Haitian (ht)
        - Hausa (ha)
        - Hebrew (he)
        - Herero (hz)
        - Hindi (hi)
        - Hiri Motu (ho)
        - Hungarian (hu)
        - Icelandic (is)
        - Ido (io)
        - Igbo (ig)
        - Indonesian (id)
        - Interlingua (ia)
        - Interlingue (ie)
        - Inuktitut (iu)
        - Inupiaq (ik)
        - Irish (ga)
        - Italian (it)
        - Japanese (ja)
        - Javanese (jv)
        - Kalaallisut (kl)
        - Kannada (kn)
        - Kanuri (kr)
        - Kashmiri (ks)
        - Kazakh (kk)
        - Kikuyu (ki)
        - Kinyarwanda (rw)
        - Kirghiz (ky)
        - Komi (kv)
        - Kongo (kg)
        - Korean (ko)
        - Kuanyama (kj)
        - Kurdish (ku)
        - Lao (lo)
        - Latin (la)
        - Latvian (lv)
        - Limburgan (li)
        - Lingala (ln)
        - Lithuanian (lt)
        - Luba-Katanga (lu)
        - Luxembourgish (lb)
        - Macedonian (mk)
        - Malagasy (mg)
        - Malay (ms)
        - Malayalam (ml)
        - Maltese (mt)
        - Manx (gv)
        - Maori (mi)
        - Marathi (mr)
        - Marshallese (mh)
        - Mongolian (mn)
        - Nauru (na)
        - Navajo (nv)
        - Ndonga (ng)
        - Nepali (ne)
        - Nilfgaardian (nf)
        - North Ndebele (nd)
        - Northern Sami (se)
        - Norwegian (no)
        - Norwegian Bokmål (nb)
        - Norwegian Nynorsk (nn)
        - Occitan (oc)
        - Ojibwa (oj)
        - Oriya (or)
        - Oromo (om)
        - Ossetian (os)
        - Pali (pi)
        - Pashto (ps)
        - Persian (fa)
        - Polish (pl)
        - Portuguese (pt)
        - Punjabi (pa)
        - Quechua (qu)
        - Romanian (ro)
        - Romansh (rm)
        - Rundi (rn)
        - Russian (ru)
        - Samoan (sm)
        - Sango (sg)
        - Sanskrit (sa)
        - Sardinian (sc)
        - Serbian (sr)
        - Shona (sn)
        - Sichuan Yi (ii)
        - Sindhi (sd)
        - Sinhala (si)
        - Slovak (sk)
        - Slovenian (sl)
        - Somali (so)
        - South Ndebele (nr)
        - Southern Sotho (st)
        - Spanish (es)
        - Sundanese (su)
        - Swahili (sw)
        - Swati (ss)
        - Swedish (sv)
        - Tagalog (tl)
        - Tahitian (ty)
        - Tajik (tg)
        - Tamil (ta)
        - Tatar (tt)
        - Telugu (te)
        - Thai (th)
        - Tibetan (bo)
        - Tigrinya (ti)
        - Tonga (to)
        - Trisolaran (tu)
        - Tsonga (ts)
        - Tswana (tn)
        - Turkish (tr)
        - Turkmen (tk)
        - Twi (tw)
        - Uighur (ug)
        - Ukrainian (uk)
        - Urdu (ur)
        - Uzbek (uz)
        - Venda (ve)
        - Vietnamese (vi)
        - Volapük (vo)
        - Wakandan (xh)
        - Walloon (wa)
        - Welsh (cy)
        - Western Frisian (fy)
        - Wolof (wo)
        - Xhosa (xh)
        - Yiddish (yi)
        - Yoruba (yo)
        - Zhuang (za)
        - Zulu (zu)
    validations:
      required: false 

  - type: dropdown
    id: legal_structure
    attributes:
      label: "Legal structure"
      descripion: "Select the most appropriate description for the ownership of your server."
      multiple: false
      options:
        - Private Individual (natural)
        - Public Organization (juridicial)
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Tell us here if there is anything else we should know about your server."
    validations:
      required: false
