---
# this file should cause schema validator errors on all 8 fields
domain:
override_description: nein
description:
override_language: nein
categories:
- cats
languages:
region: catland
legal_body_type: aristocaty
