---
# this file should fail schema validation with extra fields
domain: cat.land
description: a server where cats can share cute pictures of their humans
categories:
- food
- furry
- religion
languages: catonese
region: europe
legal_body_type: natural
programming_language: ruby
minimum_cat_number: 2
