name: check json schema validator
on: [push]

jobs:
  check-json-schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install check-jsonschema
        run: pip install check-jsonschema

      - name: Use Check-jsonschema
        run: check-jsonschema --schemafile .schema.yml servers/*
