---
name: Opt-in check
on:
  push:
    # paths:
    #   - 'default_servers/*'

jobs:
  Schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Get Changed Default Servers
        id: getfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "files=$(gh pr diff ${{ github.event.pull_request.number }} --name-only | grep '^default_servers/' | xargs -I {} basename {} .yaml | xargs)" >> $GITHUB_OUTPUT

      - name: Request Opt-in file
        if: ${{ steps.getfile.outputs.files != '' }}
        run: |
            FILES="${{ steps.getfile.outputs.files }}"
            for domain in $FILES; do
              NODEINFO=$(curl -L "http://${domain}/nodeinfo/2.0" | jq -r '.["metadata"] | .["optInServerRecommendation"]'|| echo "000")

              if [ "$NODEINFO" -ne "true" || "false" ]; then
                echo "$domain does not expose optInServerRecommendation or is not reachable"
                FAILED=$((FAILED + 1))
              elif [ "$NODEINFO" == "true" ]
                echo "$domain exposes optInServerRecommendation: $NODEINFO"
              elif [ "$NODEINFO" == "false" ]
                echo "$domain exposes optInServerRecommendation: $NODEINFO"
                FAILED=$((FAILED + 1))
              fi
            done

            if [ "$FAILED" -gt 0 ]; then
              echo "not all endpoint could be reached"
              exit 1
            fi
