name: YAML schema validator
on: [push]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: nrkno/yaml-schema-validator-github-action@v5
      with:
        schema: .schema.yaml
        target: servers/ailbhean.co-shaoghal.net.yaml
        # Uncomment to disable strict checks
        # no-strict: true
